"""initial_schema

Revision ID: 1bf6aa4e001c
Revises:
Create Date: 2026-07-13 22:40:02.151173

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1bf6aa4e001c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_unknown_faces_timestamp"), "unknown_faces", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unknown_faces_timestamp"), table_name="unknown_faces")
    # ### end Alembic commands ###
